# Generated by Django 4.2.11 on 2024-04-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='scraped_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
