# Generated by Django 5.0.4 on 2024-05-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_topic_scraped_data_alter_topic_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
